### PR TITLE
Add conditionally executed filters

### PR DESCRIPTION
**Pull request by Nusiq**
Adds `when` property to filters which can be used to run them based on specified condition.

### CODE REVIEW

**Comment by Nusiq** [comment]
I added new schema for this version. Currently I marked it as v1.1

# IMPORTANT THING TO DO BEFORE THE MERGE
We should make a decision whether the schema version should be v1 (updated) or v1.1. If we decide to update v1 then I would probably prefer to remove v1, or maybe we should make a copy of current v1 and name it v1.0? This way the users could choose if they want to see additional features in schema or not. v2 will be used when something compatibility breaking will happen to the schema. A nice thing about keeping schemas online is that we can update them and the user doesn't need to do anything but it also means that we should be careful how we do it.

**Comment by Nusiq** [comment]
I think the best solution is to keep the versions used in schemas generated by regolith with only the major number (v1, v2 etc.) but we should also keep minor versions on the schema repository. So for example if in the future we will have version v1.5, v1 will also point at it, but the user could change the config to use any schema they want.

**Comment by Nusiq** [comment]
I think I know how I want to handle schemas I described it in the README file of this commit: https://github.com/Bedrock-OSS/regolith-schemas/commit/1ca6e06cc22cf2d3a00cd0bb0fd6adbec1714d85

It still can be changed (the 1.1 version is not being used by anything yet).

**Comment by Nusiq** [comment]
The feature should also be documented.

**Comment by Nusiq** [comment]
Current changes:
- Added 'when' property to the filters
- Added tests for the use of the 'when' property
- Updated documentation

**Comment by stirante** [comment]
Could you remove those additional exe filter fields from documentation as well?
https://github.com/Bedrock-OSS/regolith/blob/conditional-filters/docs/_pages/docs/filter_types/exe-filters.md

**Review by stirante — APPROVED** [review]

**Pull request merged**
