### PR TITLE
Switch to fsnotify for watch mode

### PR DESCRIPTION
**Pull request by arexon**
This PR integrates the [fsnotify](https://github.com/fsnotify/fsnotify) library for file watching (which supports multiple major platforms).

However, as of [v1.7.0](https://github.com/fsnotify/fsnotify/releases/tag/v1.7.0), it doesn't *officially* support recursive file watching yet. Windows and Linux backends do support this on the main branch, but not macOS/BSD. As a temporary workaround, I've forked the library and [manually enabled this feature](https://github.com/arexon/fsnotify/blob/c862c914df35c4566d84a14ce12d11f58e225e47/fsnotify.go#L481), which this implementation depends on.

Once fsnotify v1.8.0 comes out with support for recursive file watching on all major platforms, we can safely remove the dependency on this fork and point to the official one instead.

Additionally, I've thoroughly tested this on both Linux and Windows and noticed no issues.

As a sidenote, fsnotify's Windows backend uses [ReadDirectoryChangesW()](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw) while Regolith's current implementation uses [FindFirstChangeNotification()](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findclosechangenotification). I've looked into both APIs and there should be no performance differences.

### CODE REVIEW

**Review by Nusiq — COMMENTED** [review]
I tested on Windows and using filters with [exportData](https://bedrock-oss.github.io/regolith/guide/online-filters#the-exportdata-property) option enabled triggers an infinite loop.

I didn't test enough to tell for sure but I think it's because in the old implementation, debouncing was different. I think it used to send signals instantly and than ignore changes for short period of time before reenabling the file watching (I might be wrong on that, I didn't read the old code, I'm just saying what I remember). In the implementation from this PR, the signals are sent with 100ms delay. I think it's better beacause it guarantees that the most recent change in a group of changes will trigger an update but it has a side affect of sending signals later.

The following code ignores the interruptions from data during exporting. This is necessary because exporting can modify `data`.
https://github.com/Bedrock-OSS/regolith/blob/88d7fee560929995de8ac05602a8556bb005aa62/regolith/profile.go#L149-L151

The exporting proces copies files from tmp to target RP, BP and back to data in some cases.


Here is an example Regolith config that uses a filter that modifies the data folder:
```json
{
	"$schema": "https://raw.githubusercontent.com/Bedrock-OSS/regolith-schemas/main/config/v1.4.json",
	"author": "Nusiq",
	"name": "test-project",
	"packs": {
		"behaviorPack": "./packs/BP",
		"resourcePack": "./packs/RP"
	},
	"regolith": {
		"dataPath": "./packs/data",
		"filterDefinitions": {
			"run_counter": {
				"url": "github.com/Nusiq/regolith-filters",
				"version": "1.0.2"
			}
		},
		"formatVersion": "1.4.0",
		"profiles": {
			"default": {
				"export": {
					"readOnly": false,
					"target": "local"
				},
				"filters": [
					{
						"filter": "run_counter"
					}
				]
			}
		}
	}
}
```

**Comment by arexon** [comment]
Interesting. I wasn't aware about the `data` interruption message being ignored during exporting.

You are right about how debouncing worked in the old implementation. I switched to sending signals every 100ms since that's pretty common, but I suppose this doesn't work well with Regolith filters possibly modifying `data` . I will switch to how debouncing worked in the old one.

Interestingly enough, the filter you provided causes a panic on Linux:

Screenshot from 2024-09-29 19-19-07

I think the root cause is `counter.txt` being written to in `data` by the filter, which is odd as this doesn't happen if you run the filter externally without Regolith.

I will have to dig more into this.

**Comment by arexon** [comment]
I fixed both issues.

The fix for the Linux panic is in the [forked fsnotify repo](https://github.com/arexon/fsnotify/blob/1ebdc44d4bc253ea83818b1e4c643dd55136ee00/backend_inotify.go#L524-L526). It's a bit of a weird issue, but I have a rough idea of what causes it: Because `run_counter` filter has the `exportData` option enabled, its data folder is being moved back and forth between `tmp` and `source`. This causes the watched path to become invalid in the `inotify` implementation.

As for Windows, the old debounced watching setup seems to work pretty nicely. It fixes the infinite loop bug. I tested this using `run_counter` filter as well.

**Comment by Nusiq** [comment]
I tested on Windows. Looks good so far. I need to set up a virtual machine to test on Linux...

**Comment by Nusiq** [comment]
I tested on a virtual machine on Linux using Nix and it mostly works but the `exportData` feature doesn't seem to work. I tested with the same regolith config I posted earlier. Regolith runs as it should, except it doesn't export the data of the `run_counter` back to the filters data folder.

Are you aware of that issue and you werent able to fix it or is it something new?

**Comment by arexon** [comment]
I looked into this and it's actually because the file watcher stops listening to events after `run_counter` data is moved back from `tmp` to `data` directory. I have no clue why this happens, but I managed to deduce the core issue to this function:

https://github.com/Bedrock-OSS/regolith/blob/624d9e732a067d6b7462a37035d2dc2df86dbe7e/regolith/file_system.go#L369-L385

I'm going to push a fix for this which completely restarts the file watcher for `data` on every export *if* at least one filter has the `exportData` option enabled.

**Comment by Nusiq** [comment]
This implementation gets locked when `regolith run` command is used on Windows, on a project that uses a filter with `exportData`. This can be observed on a project with config I mentioned earlier and in one of the tests - `TestDataModifyRemoteFilter`.

The test gets locked when it tries to run this line:
https://github.com/Bedrock-OSS/regolith/blob/4124cb046de96a8dc04df4c1679ca1681122f4ad/regolith/export.go#L369-L371

The file watching is disabled during `regolith run` which probably causes the issue when the code tries to reset it.

---

Is there a downside of reseting the watcher during export. If not I think it's a pretty clean solution which could just run every time without checking if one of the filters uses `exportData`. I think it could be better because the `watch` results will be more consistent and maybe easier to maintain in the future.

I didn't think about it too hard, but maybe with the new way we could use your previous implementation of debouncing.

**Comment by arexon** [comment]
Ah, I will fix that.

I don't think there's any inherit downside to resetting file watching during export regardless of whether `exportData` is set or not. I will look into it.

**Comment by arexon** [comment]
The watcher now pauses before exporting, waits for the process to finish, and then restarts. I switched to a single `DirWatcher` instance that handles watching RP, BP, and data at the same time. This made the process of restarting a lot simpler as we wouldn't have to maintain separate channels per instance.

Although my knowledge in Go is limited, this change really shouldn't cause any performance issues. I didn't experience any on my end.

**Comment by Nusiq** [comment]
Works almost perfectly fine but I found a small issue:

If Regolith is in a `watch` mode and it fails here at `ExportProject` it won't restart the file watching because errors from RunProfile are only logged but not handled in any way.
https://github.com/Bedrock-OSS/regolith/blob/0646a67c692f38f44cce745aa8113825ed684b9f/regolith/profile.go#L145-L154

This ends with Regolith getting stuck on the select-case of this loop waiting for signals from paused file watcher.
https://github.com/Bedrock-OSS/regolith/blob/0646a67c692f38f44cce745aa8113825ed684b9f/regolith/main_functions.go#L304-L327

**Comment by Nusiq** [comment]
I fixed it.

It's fairly easy to actually cause that issue. You just need to get regolith running in the `watch` mode, on the same test project I mentioned earlier here and create a file inside the directory of the `run_counter`. It doesn't work 100% of the times but if you try to create/delete new files multiple times in that path eventually `ExportProject` will fail.

**Pull request merged**
